spring:
  application:
    name: client-contract-api

  datasource:
    url: jdbc:postgresql://db:5432/vaudoise_db
    username: vaudoise
    password: vaudoise
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html
